[package]
name = "laminar"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nvml-wrapper = "0.8.0"
pretty-bytes = "0.2.2"
sysinfo = "0.27.1"
serde_json = "1.0"
serde = "0.9.0-rc2"